### ISSUE TITLE
Robot bugged

### ISSUE THREAD

**Issue by ViniciusAlvesPereira** [VSSSLeague/FIRASim#4]
**Describe the bug**
The blue robot with ID 0 does not move no matter what you try

**To Reproduce**
1. Just run a game with any formation using all robots from blue team.
2. See the Robot 0 not moving

**Expected behavior**
Whatever is the robot's behavior', it should at least move, right? But the one with ID 0 does not.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04 LTS

**Comment by zsmn** [comment]
Hi @ViniciusAlvesPereira, thank you for you report =D
I did some tests with the the [FIRAClient](https://github.com/VSSSLeague/FIRAClient) code and I didn't see any problems while running, the robots received the control packets normally.
Can you do the same test? Because if everything goes ok, I think it's a problem with the code you were running.

**Comment by IEEEVSS** [comment]
FIRASim is working properly. I'm closing this issue, but feel free to re-open it if this bug returns.
